- hosts: localhost
  become: no
  gather_facts: no
  name: Create in-memory inventory
  tasks:
    - name: Read terraform outputs
      command: terraform output -json
      register: _tf_outputs
    - name: Set facts from terraform outputs
      set_fact:
        cluster_ips: "{{ (_tf_outputs.stdout | from_json).ips.value }}"
        instance_ids: "{{ (_tf_outputs.stdout | from_json).ids.value }}"
    - name: Add hosts
      add_host:
        name: "{{ item.key }}"
        ansible_host: "{{ item.value }}"
        ansible_user: cloud-user
        instance_id: "{{ instance_ids[item.key ] }}"
      loop: "{{ cluster_ips | dict2items }}"
