- hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: Create in-memory inventory
      import_role:
        name: terraform
        tasks_from: inventory.yml

- hosts: all
  become: no
  gather_facts: no
  tasks:
    - command: "openstack server rebuild {{ instance_id }}"
      delegate_to: localhost
    - wait_for_connection:
