
- import_playbook: inventory.yml

- hosts: all
  become: yes
  gather_facts: no
  name: Install k3s
  tasks:
    - include_role:
        name: k3s
      vars:
        k3s_node_type: "{{ 'server' if 'control' in inventory_hostname else 'agent' }}"
        ks3_token:  nzeSGBpI.Fo22YoBGGSNzH2Y4 # [a-z0-9]{6}.[a-z0-9]{16}
        k3s_server_address: "{{ hostvars['k3s-control'].ansible_host }}" # assuming internal DNS is broken!
