- name: Write Munge key
  copy:
    content: "{{ slurm_munge_key | b64decode }}"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: 0400

- name: Restart munge
  systemd:
    name: munge
    state: restarted
    enabled: true

- name: Create slurm.conf
  template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
  when: slurm_role == 'control'

- name: Configure slurmd with control address
  # this is hacky - it finds the partition assuming a nodename of form clustername-partname-index
  copy:
    content: "SLURMD_OPTIONS='-Z --conf Feature={{ (inventory_hostname | split('-'))[1] }} --conf-server {{ slurm_control_address }}'"
    dest: /etc/sysconfig/slurmd
  when: slurm_role == 'compute'

- name: Restart slurm service
  systemd:
    name: "{{ slurm_service[slurm_role] }}"
    state: restarted
    enabled: true
  vars:
    slurm_service:
      control: slurmctld
      compute: slurmd
