- name: Read terraform outputs
  command: "terraform -chdir={{ terraform_project_path }} output -json"
  register: _tf_outputs

- name: Set facts from terraform outputs
  set_fact:
    cluster_nodes: "{{ (_tf_outputs.stdout | from_json).cluster_nodes.value }}"

- debug:
    msg: "{{ cluster_nodes | to_nice_yaml }}"


- name: Add hosts
  add_host:
    name: "{{ item.name }}"
    ansible_host: "{{ item.ip }}"
    instance_id: "{{ item.id }}"
    groups: "{{ item.groups }}"
  loop: "{{ cluster_nodes }}"
