- name: Read terraform outputs
  command: "terraform -chdir={{ terraform_project_path }} output -json"
  register: _tf_outputs

- name: Set facts from terraform outputs
  set_fact:
    cluster_ips: "{{ (_tf_outputs.stdout | from_json).ips.value }}"
    instance_ids: "{{ (_tf_outputs.stdout | from_json).ids.value }}"

- name: Add hosts
  add_host:
    name: "{{ item.key }}"
    ansible_host: "{{ item.value }}"
    instance_id: "{{ instance_ids[item.key ] }}"
  loop: "{{ cluster_ips | dict2items }}"
